version: '3.7'

services:
  schautocompletebe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schautocompletebe
    image: schoology/backlaravel
    volumes:
      - .:/app
      - /app/vendor
    ports:
      - 8000:8000
    networks:
      - schoology-network
    command: >
      bash -c "cp .env.example .env
      && php artisan key:generate
      && php artisan serve --host=0.0.0.0 --port=8000"

networks:
  schoology-network:
    driver: bridge